# Generated by Django 5.1.6 on 2025-03-29 16:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalGovernment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='reports/')),
                ('video_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Borehole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borehole_id', models.CharField(max_length=30, null=True, unique=True)),
                ('Address', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=20, null=True)),
                ('installed_date', models.DateField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('IN-PROGRESS', 'In-progress'), ('IN-ACTIVE', 'In-active')], default='Active', max_length=50)),
                ('local_government', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boreholes', to='core.localgovernment')),
            ],
        ),
        migrations.CreateModel(
            name='Orphan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('Dob', models.DateField(null=True)),
                ('address', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=20, null=True)),
                ('next_of_kin', models.CharField(max_length=20, null=True)),
                ('registered_date', models.DateField(auto_now_add=True)),
                ('local_government', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orphans', to='core.localgovernment')),
            ],
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('coordinator', 'Coordinator'), ('technical', 'Technical')], default='coordinator', max_length=50)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
