# Generated by Django 4.1.13 on 2025-05-23 07:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalGovernment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='reports/')),
                ('video_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('coordinator', 'Coordinator'), ('regional coordinator', 'regional coordinator'), ('head', 'Head')], default='coordinator', max_length=50)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(default='Nigeria', max_length=50)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staffprofile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Orphan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('Dob', models.DateField(null=True)),
                ('address', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=20, null=True)),
                ('next_of_kin', models.CharField(max_length=20, null=True)),
                ('registered_date', models.DateField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='reports/')),
                ('local_government', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orphans', to='core.localgovernment')),
            ],
        ),
        migrations.CreateModel(
            name='Borehole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borehole_id', models.CharField(max_length=30, null=True, unique=True)),
                ('location', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=20, null=True)),
                ('installed_date', models.DateField(auto_now_add=True)),
                ('Depth', models.IntegerField()),
                ('status', models.CharField(choices=[('OPERATIONAL', 'Operational'), ('MAINTENANCE REQUIRED', 'Maintenance-required'), ('NON-OPERATIONAL', 'Non-operational')], default='Operational', max_length=50)),
                ('water_quality', models.CharField(choices=[('EXCELLENCT', 'Excellent'), ('GOOD', 'Good'), ('FAIR', 'Fair'), ('POOR', 'Poor')], default='Excellent', max_length=20)),
                ('Last_Serviced', models.DateTimeField()),
                ('funded_by', models.CharField(default='betul abla foundation', max_length=150)),
                ('local_government', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boreholes', to='core.localgovernment')),
            ],
        ),
    ]
