# Generated by Django 5.2 on 2025-04-12 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borehole',
            name='installed_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='role',
            field=models.CharField(choices=[('coordinator', 'Coordinator'), ('head', 'Head')], default='coordinator', max_length=50),
        ),
    ]
