# Generated by Django 5.2 on 2025-04-12 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_borehole_installed_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orphan',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='reports/'),
        ),
    ]
