# Generated by Django 4.1.13 on 2025-04-22 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_staffprofile_country_alter_staffprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
