# Generated by Django 4.1.13 on 2025-04-29 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_staffprofile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localgovernment',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
